name: CMR
favicon: null
layout_spectrum: 0.18962949072010815
typography_spectrum: 0.19865330285392702
title: Little Eagle Marketing Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7817955366335809
  lightness: 0.5954726743511856
  saturation: 0.04000097536481917
  rhythmicContrast: 0.9633633478078991
purpose: []
